### PR TITLE
Plotly change size

### PR DESCRIPTION
**Pull request by samwaseda**
Since the frame is generally super small, I made a larger default size

Update following @liamhuber's comment below.

Before:

Screenshot 2024-02-08 at 19 46 53

After (default height, but can obviously be changed):

Screenshot 2024-02-08 at 19 48 05

### CODE REVIEW

**Review by liamhuber — APPROVED** [review]
Lgtm. Not a neg just an fyi, this type of UI PR is perfect for snagging before and after screenshots and dragging them into the PR description! 🚀

**Comment by samwaseda** [comment]
> Lgtm. Not a neg just an fyi, this type of UI PR is perfect for snagging before and after screenshots and dragging them into the PR description! 🚀

I updated it!

**Comment by liamhuber** [comment]
> > Lgtm. Not a neg just an fyi, this type of UI PR is perfect for snagging before and after screenshots and dragging them into the PR description! 🚀
> 
> I updated it!

Nice! I always trusted you that the change made things better, but now I can agree with you that the change makes things better :joy:

**Review by jan-janssen — CHANGES_REQUESTED** [review]
Can you add a warning when the height was changed but `NGLview` or `ASE` is used for plotting? Just to tell the users that this feature is currently only available for `plotly`.

**Review by jan-janssen — APPROVED** [review]
Looks good to me

**Comment by jan-janssen** [comment]
As soon as this pull request is merged I create a new release of `structuretoolkit`.

**Pull request merged**
