### PR TITLE
Use `get_atomic_numbers` instead of `atomic_numbers`

### PR DESCRIPTION
**Pull request by samwaseda**
Waiting for https://github.com/pyiron/pyiron_atomistics/pull/1057

### CODE REVIEW

**Review by jan-janssen — CHANGES_REQUESTED** [review]
Is not the `parent=True` option pyiron specific? The goal for the `structuretoolkit`is to be completely based on ASE Atoms.

**Comment by samwaseda** [comment]
> Is not the `parent=True` option pyiron specific? The goal for the `structuretoolkit`is to be completely based on ASE Atoms.

Ah good point. Let me think about it.

**Comment by samwaseda** [comment]
Do you know whether it's actually possible to change the chemical symbols in ASE? I take a quick look at it and I couldn't find it.

**Comment by jan-janssen** [comment]
> Do you know whether it's actually possible to change the chemical symbols in ASE? I take a quick look at it and I couldn't find it.

I guess the only special element they have is `X`: 
https://gitlab.com/ase/ase/-/blob/master/ase/data/__init__.py#L12
```
from ase.atom import Atom
from ase.atoms import Atoms
structure = Atoms([Atom("X")])
print(structure.get_positions(), structure.cell)
```

**Comment by jan-janssen** [comment]
For changing elements you can use: 
https://github.com/pyiron/structuretoolkit/blob/main/structuretoolkit/common/helper.py#L130
```
structure.symbols = element_lst 
```

**Comment by jan-janssen** [comment]
That's why I use `pyiron_to_ase()` in https://github.com/pyiron/pyiron_atomistics/pull/1053 but I agree pyiron to ASE currently just ignores extra elements.

**Comment by jan-janssen** [comment]
I have to admit I was not aware that ASE had an `get_atomic_numbers()` function. But in this case I guess we can remove: 
```
def get_atomic_numbers(structure):
    return structure.get_atomic_numbers()
```
And instead replace the `get_atomic_numbers(structure)` calls with `structure.get_atomic_numbers()`.

**Comment by samwaseda** [comment]
> I have to admit I was not aware that ASE had an `get_atomic_numbers()` function. But in this case I guess we can remove:
> 
> ```
> def get_atomic_numbers(structure):
>     return structure.get_atomic_numbers()
> ```
> 
> And instead replace the `get_atomic_numbers(structure)` calls with `structure.get_atomic_numbers()`.

I wasn't either :D but I guess then we found the optimal solution

**Comment by jan-janssen** [comment]
> sorry a mistake, just a moment

I am happy - at least the tests failed ;-)

**Pull request merged**
